module.exports = {
    'funcLight':             {en: 'Light',            de: 'Licht',            ru: 'Свет',                     fr: 'Lumière',               nl: 'Licht'},
    'funcHeating':           {en: 'Heating',          de: 'Heizung',          ru: 'Обогрев',                  fr: 'Chauffage',             nl: 'Verwarming'},
    'funcClimateControl':    {en: 'Climate сontrol',  de: 'Klima-Steuerung',  ru: 'Климатический контроль',   fr: 'Climate control',       nl: 'Climate сontrol'},
    'funcWeather':           {en: 'Weather',          de: 'Wetter',           ru: 'Погода',                   fr: 'Météo',                 nl: 'Weer'},
    'funcEnvironment':       {en: 'Environment',      de: 'Umgebung',         ru: 'Окружающая среда',         fr: 'Environnement',         nl: 'Milieu'},
    'funcSecurity':          {en: 'Security',         de: 'Sicherheit',       ru: 'Безопасность',             fr: 'Sécurité',              nl: 'Veiligheid'},
    'funcLock':              {en: 'Lock',             de: 'Sperren',          ru: 'Замок',                    fr: 'Fermer à clé',          nl: 'Slot'},
    'funcButton':            {en: 'Button',           de: 'Taste',            ru: 'Button',                   fr: 'Bouton',                nl: 'Knop'},
    'funcCentral':           {en: 'Central',          de: 'Zentral',          ru: 'Центральный',              fr: 'Central',               nl: 'Central'},
    'funcEnergy':            {en: 'Energy',           de: 'Energie',          ru: 'Энергия',                  fr: 'Énergie',               nl: 'Energie'},
    'roomLivingRoom':        {en: 'LivingRoom',       de: 'Wohnzimmer',       ru: 'Гостиная',                 fr: 'Salon',                 nl: 'Woonkamer'},
    'roomKitchen':           {en: 'Kitchen',          de: 'Küche',            ru: 'Кухня',                    fr: 'Cuisine',               nl: 'Keuken'},
    'roomBedroom':           {en: 'Bedroom',          de: 'Schlafzimmer',     ru: 'Спальня',                  fr: 'Chambre',               nl: 'Slaapkamer'},
    'roomChildrensRoom1':    {en: 'Childrens room 1', de: 'Kinderzimmer 1',   ru: 'Детская комната 1',        fr: 'Salle des enfants 1',   nl: 'Kinderkamer 1'},
    'roomChildrensRoom2':    {en: 'Childrens room 2', de: 'Kinderzimmer 2',   ru: 'Детская комната 2',        fr: 'Chambre des enfants 2', nl: 'Kinderkamer 2'},
    'roomOffice':            {en: 'Office',           de: 'Büro',             ru: 'Офис',                     fr: 'Bureau',                nl: 'Kantoor'},
    'roomBathroom':          {en: 'Bathroom',         de: 'Bad',              ru: 'Ванная комната',           fr: 'Salle de bains',        nl: 'Badkamer'},
    'roomGarage':            {en: 'Garage',           de: 'Garage',           ru: 'Гараж',                    fr: 'Garage',                nl: 'Garage'},
    'roomHWR':               {en: 'HWR',              de: 'HWR',              ru: 'HWR',                      fr: 'HWR',                   nl: 'HWR'},
    'roomGarden':            {en: 'Garden',           de: 'Garten',           ru: 'Сад',                      fr: 'Jardin',                nl: 'Tuin'},
    'roomTerrace':           {en: 'Terrace',          de: 'Terrasse',         ru: 'Терраса',                  fr: 'Terrasse',              nl: 'Terras'}
};
